language: groovy
jdk:
  - openjdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - chmod +x gradlew
script: travis_wait 5 ./gradlew -Dfile.encoding=UTF-8 test
after_success:
  - bash <(curl -s https://codecov.io/bash)
